### ISSUE TITLE
我不明白我哪有问题。。。

### ISSUE THREAD

**Issue by djs326** [Haocen2004/genshin-dailynote-helper#10]
登录失败

**Comment by GitHub-JingYi** [comment]
我也遇到了一样的问题

**Comment by Haocen2004** [comment]
> 登录失败

已了解 正在尝试复现
以及记得保护好你的cookie

**Comment by GitHub-JingYi** [comment]
已解决了哈哈，是我填的cookie有问题，感谢！

**Comment by djs326** [comment]
> 

哥，咋整的

**Comment by GitHub-JingYi** [comment]
就按照他的说明来的，
只用 cookie 中 login_ticket 项，
运行 node cookie.js <login_ticket>，
程序会自动修改 config.json 中的cookie值。
COOKIE格式是stuid=xxx;stoken=xxx;ltuid=xxx;ltoken=xxx;account_id=xxx;login_ticket=xxx;cookie_token=xxx;

**Comment by djs326** [comment]
> 就按照他的说明来的， 只用 cookie 中 login_ticket 项， 运行 node cookie.js <login_ticket>， 程序会自动修改 config.json 中的cookie值。 COOKIE格式是stuid=xxx;stoken=xxx;ltuid=xxx;ltoken=xxx;account_id=xxx;login_ticket=xxx;cookie_token=xxx;

感谢老哥
我成功了
