### ISSUE TITLE
云函数调用失败，经排查发现playerData.is_chosen的值为false导致

### ISSUE THREAD

**Issue by Kenny-Ch** [Haocen2004/genshin-dailynote-helper#11]
![image](https://user-images.githubusercontent.com/54130213/154480044-a630ea56-dd13-4dd2-a6ce-e76cca5d1287.png)
```
if (playerData.is_chosen) {
      cache['userData'][playerData.game_biz ] = playerData;
      logger.i(util.format('玩家数据已更新 game_biz: %s', playerData.game_biz));	
    }
```

**Comment by Haocen2004** [comment]
`Notice | 注意事项
查询的角色为米游社中选择的默认角色`
请前往米游社绑定默认角色
打开app 右下角 我的 -> 我的角色 右上角角色管理
![IMG_20220217_202333.jpg](https://user-images.githubusercontent.com/25221696/154481163-2961c28f-43c5-4bf8-a762-8a93e1d10f28.jpg)

**Comment by Haocen2004** [comment]
以及 同 #8
建议善用搜索

**Comment by Kenny-Ch** [comment]
好的谢谢！我之前下意识只看了open的issue，刚刚看了closed的才发现有人提了一样的😂，我也是把那个判断删了就可以了/捂脸
