### ISSUE TITLE
做了一个新的KWGT插件

### ISSUE THREAD

**Issue by WinkeyLin** [Haocen2004/genshin-dailynote-helper#4]
今天从 NGA 偶然得知大佬的这个项目，身为 KWGT 爱好者的我欣喜若狂，花一个晚上做了一个新的插件。冒昧开个 Issue 分享出来，希望能有所帮助~

下载链接：https://winkeylin.lanzoup.com/iXvjMxm7csh
使用方法已经写在插件里了

效果图：
![IMG_20211215_001004.jpg](https://user-images.githubusercontent.com/56619122/146035653-9904d4d6-4502-4bec-91a7-77b23b092bbf.jpg)
![IMG_20211215_001239.jpg](https://user-images.githubusercontent.com/56619122/146036134-a005fb6b-291e-45b4-bd01-ab6c27ab700d.jpg)

**Comment by Haocen2004** [comment]
好诶
有空给你安排到readme里面去（

**Comment by Haocen2004** [comment]
感谢分享 已经合并至readme.md
