### ISSUE TITLE
昨天米友社查询树脂的api好像更新了

### ISSUE THREAD

**Issue by Fnvelope** [Haocen2004/genshin-dailynote-helper#6]
可以有时间更新一下吗

**Comment by Haocen2004** [comment]
已更新

**Comment by Fnvelope** [comment]
测试了几次,本地的能够获取到数据,云函数版不行,不知道是哪里的问题

**Comment by Haocen2004** [comment]
> 测试了几次,本地的能够获取到数据,云函数版不行,不知道是哪里的问题

请拉取最新代码 release处暂未更改

**Comment by Fnvelope** [comment]
> > 测试了几次,本地的能够获取到数据,云函数版不行,不知道是哪里的问题
> 
> 请拉取最新代码 release处暂未更改

我确实是下的最新的代码

**Comment by Fnvelope** [comment]
- 这是报错的日志
-
![20211225185955](https://user-images.githubusercontent.com/54101846/147383578-da327257-429b-4c23-8934-cdc6f92546be.png)

**Comment by Haocen2004** [comment]
> - 这是报错的日志
> -
> ![20211225185955](https://user-images.githubusercontent.com/54101846/147383578-da327257-429b-4c23-8934-cdc6f92546be.png)
>  

仔细阅读一下readme git下载的zip内文件夹名会一直变就很烦（

**Comment by Fnvelope** [comment]
> > * 这是报错的日志
> > 
> > 
> > ![20211225185955](https://user-images.githubusercontent.com/54101846/147383578-da327257-429b-4c23-8934-cdc6f92546be.png)
> 
> 仔细阅读一下readme git下载的zip内文件夹名会一直变就很烦（

我后面自行修改了bootstrap里cd genshin-dailynote-helper-1.1.1这里,后面只能偶尔获取到数据.
和别人讨论了下貌似是新的接口添加了防火墙,对腾讯云函数的效果拔群.
不知道能否部署到其他的云函数服务器上

**Comment by Fnvelope** [comment]
请问如果部署到阿里云 函数入口应该填什么
