### ISSUE TITLE
关于refPlayer文件中的is_chosen

### ISSUE THREAD

**Issue by zqp111** [Haocen2004/genshin-dailynote-helper#8]
在[lib/mihoyo/refPlayer.js](https://github.com/Haocen2004/genshin-dailynote-helper/blob/main/lib/mihoyo/refPlayer.js)中，获取玩家数据时，判断了is_chosen进行玩家数据的更新。但是根据我自己的数据，我的is_chosen值为false，把这个判断取消后测试功能正常。请问这里判断的原因是什么呢，我直接取消这个判断是否会在一些地方出现错误呢？感谢~

**Comment by Haocen2004** [comment]
这是官方用来标记默认角色的
一个米游社账号可以绑定多个原神账号（不同渠道）
单绑定可无视

**Comment by Haocen2004** [comment]
![IMG_20220109_233252.jpg](https://user-images.githubusercontent.com/25221696/148689134-261bfa22-1c97-4b14-84a5-5d0bbe2ce108.jpg)
附图片说明 以三蹦子为例 原神同理
